ALTER TABLE RESTAURANTS ADD COLUMN CUISINE varchar(255);
ALTER TABLE RESTAURANTS ADD COLUMN CITY varchar(255);
ALTER TABLE RESTAURANTS ADD COLUMN COUNTRY varchar(255);
ALTER TABLE RESTAURANTS ADD COLUMN COUNTRYCODE varchar(10);
ALTER TABLE RESTAURANTS ADD COLUMN URL varchar(255);
